// 此文件由 src-tauri/build.rs 自动生成，请勿手动修改。
// 单一事实来源：src-tauri/src/constants.rs

export const SIZE_BASE = 1000 as const

// Analyze EntryRow 副标题：文件扩展名（小写、不含点）→ 类型描述
export const FILE_TYPE_DESCS: Record<string, string> = {
  'zip': 'ZIP 归档',
  'rar': 'RAR 压缩包',
  '7z': '7-Zip 归档',
  'tar': 'TAR 归档',
  'gz': 'GZip 归档',
  'bz2': 'BZip2 归档',
  'xz': 'XZ 归档',
  'iso': 'ISO 磁盘映像',
  'dmg': '磁盘映像',
  'pkg': '安装器软件包',
  'ipa': 'iOS 应用包',
  'apk': 'Android 应用包',
  'png': 'PNG 图像',
  'jpg': 'JPEG 图像',
  'jpeg': 'JPEG 图像',
  'heic': 'HEIF 图像',
  'gif': 'GIF 图像',
  'svg': 'SVG 图像',
  'tiff': 'TIFF 图像',
  'webp': 'WebP 图像',
  'psd': 'Photoshop 文档',
  'icns': '图标文件',
  'mp4': 'MPEG-4 影片',
  'mov': 'QuickTime 影片',
  'mkv': 'Matroska 视频',
  'avi': 'AVI 影片',
  'wmv': 'Windows Media 视频',
  'm4v': 'iTunes 视频',
  'webm': 'WebM 视频',
  'mp3': 'MP3 音频',
  'wav': '波形音频',
  'flac': 'FLAC 无损音频',
  'aac': 'AAC 音频',
  'm4a': 'MPEG-4 音频',
  'aiff': 'AIFF 音频',
  'pdf': 'PDF 文档',
  'doc': 'Word 文档',
  'docx': 'Word 文档',
  'xls': 'Excel 电子表格',
  'xlsx': 'Excel 电子表格',
  'ppt': 'PowerPoint 演示文稿',
  'pptx': 'PowerPoint 演示文稿',
  'txt': '纯文本',
  'md': 'Markdown 文档',
  'epub': 'EPUB 电子书',
  'dylib': 'Mach-O 动态库',
  'jar': 'Java 归档',
  'sqlite': 'SQLite 数据库',
  'db': '数据库文件',
  'ttf': 'TrueType 字体',
  'otf': 'OpenType 字体',
  'exe': 'Windows 可执行文件',
} as const

// Analyze EntryRow 副标题：目录名后缀（含点）→ 类型描述（.app 等目录型 bundle）
export const BUNDLE_TYPE_DESCS: Record<string, string> = {
  '.app': '应用程序',
  '.bundle': '资源束',
  '.framework': '框架',
  '.simruntime': '模拟器运行时',
  '.dsym': '调试符号',
  '.xcodeproj': 'Xcode 工程',
  '.xcworkspace': 'Xcode 工作区',
} as const
