pub const MOLE_COMMANDS: [(&str, &str); 14] = [
    ("clean", "Free up disk space"),
    ("uninstall", "Remove apps completely"),
    ("optimize", "Check and maintain system"),
    ("optimise", "Check and maintain system"),
    ("analyze", "Explore disk usage"),
    ("status", "Monitor system health"),
    ("purge", "Remove old project artifacts"),
    ("installer", "Find and remove installer files"),
    ("touchid", "Configure Touch ID for sudo"),
    ("completion", "Setup shell tab completion"),
    ("update", "Update to latest version"),
    ("remove", "Remove Mole from system"),
    ("help", "Show help"),
    ("version", "Show version"),
];
